services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: foobar
      PGDATA: /var/lib/postgres